# Generated by Django 2.1.7 on 2019-03-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionholder',
            name='card',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False')], default='False', help_text='This will store the use of card', max_length=5, verbose_name='Card In Use'),
        ),
    ]
