# Generated by Django 2.1.7 on 2019-03-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='odr',
            field=models.CharField(help_text='If the order is created and procced to pay then only it will store the order id  <year>_<month>@<day>_<sl_no>', max_length=50, unique=True, verbose_name='Order Id'),
        ),
    ]
