# Generated by Django 2.1.7 on 2019-03-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='u_type',
            field=models.CharField(choices=[('stud', 'Student'), ('ment', 'Mentor'), ('exam', 'Examinations'), ('acc', 'Accounts')], help_text='This is the type of user using it', max_length=20, verbose_name='User Type'),
        ),
    ]
