# Generated by Django 2.1.7 on 2019-03-19 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190319_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='id',
            new_name='id_user',
        ),
    ]
