# Generated by Django 2.1.7 on 2019-03-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('emp_id', models.CharField(help_text="Enter the Mentor's Teacher's ID", max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Teacher ID')),
                ('name', models.CharField(help_text='Name of your Mentor', max_length=40, verbose_name="Mentor's Name")),
                ('contact', models.BigIntegerField(help_text="Enter the Mentor's Contact No", unique=True, verbose_name='Contact Number')),
                ('dept', models.CharField(help_text="Enter the Mentor's Department", max_length=50, verbose_name='Department')),
                ('pos', models.CharField(choices=[('ASS_P', 'Ass. Professor'), ('ASO_P', 'Aso. Professor'), ('PROF', 'Professor'), ('HOD', 'Head Of Department')], help_text="Enter the Mentor's Post", max_length=40, verbose_name='Post')),
            ],
        ),
    ]
