# Generated by Django 2.1.7 on 2019-04-12 15:43

from django.db import migrations, models
import mentor.models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='dp',
            field=models.ImageField(default='dp/default/default.png', help_text='This is the Profile Pictuer of the Mentor', upload_to=mentor.models.upload_to, verbose_name='Profile Picture'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='id_fet',
            field=models.IntegerField(blank=True, default=1, help_text='unique ID wrt College', verbose_name='Unique ID'),
            preserve_default=False,
        ),
    ]
