# Generated by Django 2.1.7 on 2019-03-14 18:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import student.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('college_id', models.CharField(help_text='Enter the college roll number', max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='Collge Id')),
                ('ojee', models.ImageField(default='DocStore/None/no_image.png', help_text='Upload the screenshot of your ojee Concent Letter', unique=True, upload_to='DocStore/', verbose_name='OJEE Concent Letter')),
                ('pass10_certi', models.ImageField(default='DocStore/None/no_image.png', help_text='Upload your 10th Pass Certifiacte(scaned image)', unique=True, upload_to='DocStore/', verbose_name='10th Pass Certificate')),
                ('mark10_sheet', models.ImageField(default='DocStore/None/no_image.png', help_text='Upload your 10th Marksheet(scaned image)', unique=True, upload_to='DocStore/', verbose_name='10th Marksheet')),
                ('pass12_certi', models.ImageField(default='DocStore/None/no_image.png', help_text='Upload your 12th Pass Certifiacte(scaned image)', unique=True, upload_to='DocStore/', verbose_name='12th Pass Certificate')),
                ('mark12_sheet', models.ImageField(default='DocStore/None/no_image.png', help_text='Upload your 12th Marksheet(scaned image)', unique=True, upload_to='DocStore/', verbose_name='12th Marksheet')),
                ('clc', models.ImageField(default='DocStore/None/no_image.png', help_text='Upload your College Leaving Certificate', unique=True, upload_to='DocStore/', verbose_name='College Leaving Cetificate')),
                ('stud_img', models.ImageField(default='DocStore/None/no_image.png', help_text='Upload your Migration Certificate', unique=True, upload_to='DocStore/', verbose_name='Migration Certificate')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(help_text="Name of Student's Father", max_length=60, verbose_name="Father's Name")),
                ('father_occu', models.CharField(help_text="Occupation of Student's Father", max_length=60, verbose_name="Fathers's Occupation")),
                ('father_contact', models.BigIntegerField(help_text="Ckontact No of Student's Father", verbose_name="Father's Contact No")),
                ('mother_name', models.CharField(help_text="Name of Student's Mother", max_length=60, verbose_name="Mother's Name")),
                ('mother_occu', models.CharField(default='House Wife', help_text="Occupation fo Student's Mother(edit it if she has a occupation)", max_length=60, verbose_name="Mother's Occupation")),
                ('mother_contact', models.BigIntegerField(help_text="Contact No Of Student's Mother", verbose_name="Mother's Contact No")),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sl_no', models.IntegerField()),
                ('reg_no', models.BigIntegerField(help_text='It is the registration number allocated by BPUT', primary_key=True, serialize=False, unique=True, validators=[student.validators.validate_registor_no, student.validators.validate_register_content], verbose_name='Registration Number')),
                ('college_id', models.CharField(help_text='It is the college assigned Roll No.', max_length=8, unique=True, verbose_name='College Roll No')),
                ('first_name', models.CharField(help_text='First Name of student', max_length=30, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, help_text='Middle name of the student(if have or leave it.).', max_length=30, verbose_name='Middle Name')),
                ('last_name', models.CharField(help_text='Last name of the student.', max_length=30, verbose_name='Last Name')),
                ('dob', models.DateField(help_text='Select your Date Of Birth', verbose_name='Date Of Birth')),
                ('join_year', models.DateField(default=datetime.datetime(2019, 3, 14, 18, 41, 0, 222018, tzinfo=utc), help_text='Select your date of join the college', verbose_name='DOJ')),
                ('course', models.CharField(choices=[('B.tech', (('CSE', 'Computer Science Engineering'), ('ETC', 'Electronic Telecommunication Engineering'), ('EE', 'Electrical Engineering'), ('CE', 'Chemical Engineering'), ('ME', 'Mechanical Engineering'), ('CVE', 'Civil Engineering'), ('CSIT', 'Computer Science And Information Technology'), ('AIEE', 'Apllied Instrumental Electronic Engineering'), ('MARINE', 'Marine Engineering'))), ('M.B.A', (('FIN', 'Finance'), ('HR', 'Human Resource'), ('ACC', 'Accounts'), ('RD', 'Rural Development'), ('OL', 'Operation And Logistics'), ('MAR', 'Marketing'))), ('Hotel Management', (('FD', 'Front Desk'), ('KIT', 'Kitchen'), ('RS', 'Room Service'), ('FP', 'Food Production'))), ('M.Sc', (('PHY', 'Physics'), ('CHEM', 'Chemistry'))), ('MCA', 'Master In Computer Application'), ('Diploma', (('IT', 'Information Technology'), ('CIVIL', 'Civil'), ('ELE', 'Electrical'), ('MECH', 'Mechanical')))], default='B.Tech', help_text='Enter the Course of Student', max_length=5, verbose_name='Course Of Study')),
                ('email', models.EmailField(help_text='Enter Your E-Mail', max_length=254, verbose_name='E-Mail')),
                ('mobile1', models.BigIntegerField(help_text='Enter your Personal Contact', unique=True, verbose_name='Personal Contact')),
                ('mobile2', models.BigIntegerField(blank=True, help_text='Enter your First Aletnative Contact', null=True, verbose_name='Alternative Contact-I')),
                ('semester', models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester'), ('3', '3rd Semester'), ('4', '4th Semester'), ('5', '5th Semester'), ('6', '6th Semester'), ('7', '7th Semester'), ('8', '8th Semester')], default='1st Semester', help_text='select your Semester', max_length=1, verbose_name='Semester')),
                ('acc_year', models.CharField(choices=[('first', 'First Year'), ('second', 'Secend Year'), ('third', 'Third Year'), ('fourth', 'Fourth Year')], default='First Year', help_text='Select your Accademic Year', max_length=6, verbose_name='Accademic Year')),
                ('pay_id', models.CharField(default='', editable=False, help_text='This will store the unique paymnet id for the student', max_length=30, unique=True, verbose_name='Payment Id')),
                ('ment', models.ForeignKey(help_text='Select Your Mentor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentor.Mentor', verbose_name='Mentor')),
            ],
        ),
        migrations.AddField(
            model_name='parent',
            name='student',
            field=models.ForeignKey(default='', help_text='Select the Students from the list given.(if not present add it)', on_delete=django.db.models.deletion.CASCADE, to='student.Student', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='document',
            name='student',
            field=models.OneToOneField(help_text='Select Registration Number with Name(if not present add it)', on_delete=django.db.models.deletion.CASCADE, related_name='Document', to='student.Student'),
        ),
    ]
