# Generated by Django 2.1.7 on 2019-03-15 07:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='join_year',
            field=models.DateField(default=datetime.datetime(2019, 3, 15, 7, 51, 29, 100383, tzinfo=utc), help_text='Select your date of join the college', verbose_name='DOJ'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pay_id',
            field=models.CharField(default='', editable=False, help_text='This will store the unique paymnet id for the student', max_length=40, unique=True, verbose_name='Payment Id'),
        ),
    ]
