# Generated by Django 2.1.7 on 2019-03-15 08:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190315_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='mig',
            field=models.ImageField(default='DocStore/None/no_image.png', help_text='Upload your Migration Certificate', unique=True, upload_to='DocStore/', verbose_name='Migration Certificate'),
        ),
        migrations.AlterField(
            model_name='document',
            name='stud_img',
            field=models.ImageField(default='DocStore/None/no_image.png', help_text='Upload your Passport Photo of Yours', unique=True, upload_to='DocStore/', verbose_name='Identification Photo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='join_year',
            field=models.DateField(default=datetime.datetime(2019, 3, 15, 8, 28, 2, 11496, tzinfo=utc), help_text='Select your date of join the college', verbose_name='DOJ'),
        ),
    ]
