# Generated by Django 2.1.7 on 2019-03-15 08:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20190315_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='join_year',
            field=models.DateField(default=datetime.datetime(2019, 3, 15, 8, 43, 48, 8176, tzinfo=utc), help_text='Select your date of join the college', verbose_name='DOJ'),
        ),
    ]
