# Generated by Django 2.1.7 on 2019-03-16 14:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20190315_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='student',
            field=models.OneToOneField(help_text='Select Registration Number with Name(if not present add it)', on_delete=django.db.models.deletion.CASCADE, related_name='Doc', to='student.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='join_year',
            field=models.DateField(default=datetime.datetime(2019, 3, 16, 14, 47, 36, 174190, tzinfo=utc), help_text='Select your date of join the college', verbose_name='DOJ'),
        ),
    ]
