# Generated by Django 2.1.7 on 2019-03-23 07:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20190323_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='join_year',
            field=models.DateField(default=datetime.datetime(2019, 3, 23, 7, 43, 29, 994491, tzinfo=utc), help_text='Select your date of join the college', verbose_name='DOJ'),
        ),
    ]
