# Generated by Django 2.1.7 on 2019-04-11 04:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20190408_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='clc',
            field=models.ImageField(help_text='Upload your College Leaving Certificate', unique=True, upload_to='', verbose_name='College Leaving Cetificate'),
        ),
        migrations.AlterField(
            model_name='document',
            name='mark10_sheet',
            field=models.ImageField(help_text='Upload your 10th Marksheet(scaned image)', unique=True, upload_to='', verbose_name='10th Marksheet'),
        ),
        migrations.AlterField(
            model_name='document',
            name='mark12_sheet',
            field=models.ImageField(help_text='Upload your 12th Marksheet(scaned image)', unique=True, upload_to='', verbose_name='12th Marksheet'),
        ),
        migrations.AlterField(
            model_name='document',
            name='mig',
            field=models.ImageField(help_text='Upload your Migration Certificate', unique=True, upload_to='', verbose_name='Migration Certificate'),
        ),
        migrations.AlterField(
            model_name='document',
            name='ojee',
            field=models.ImageField(help_text='Upload the screenshot of your ojee Concent Letter', unique=True, upload_to='', verbose_name='OJEE Concent Letter'),
        ),
        migrations.AlterField(
            model_name='document',
            name='pass10_certi',
            field=models.ImageField(help_text='Upload your 10th Pass Certifiacte(scaned image)', unique=True, upload_to='', verbose_name='10th Pass Certificate'),
        ),
        migrations.AlterField(
            model_name='document',
            name='pass12_certi',
            field=models.ImageField(help_text='Upload your 12th Pass Certifiacte(scaned image)', unique=True, upload_to='', verbose_name='12th Pass Certificate'),
        ),
        migrations.AlterField(
            model_name='document',
            name='stud_img',
            field=models.ImageField(help_text='Upload your Passport Photo of Yours', unique=True, upload_to='', verbose_name='Identification Photo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='join_year',
            field=models.DateField(default=datetime.datetime(2019, 4, 11, 4, 58, 58, 570881, tzinfo=utc), help_text='Select your date of join the college', verbose_name='DOJ'),
        ),
    ]
