# Generated by Django 2.1.7 on 2019-04-12 15:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_auto_20190412_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='join_year',
            field=models.DateField(default=datetime.datetime(2019, 4, 12, 15, 37, 8, 443831, tzinfo=utc), help_text='Select your date of join the college', verbose_name='DOJ'),
        ),
    ]
