# Generated by Django 2.1.7 on 2019-04-18 15:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_auto_20190412_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='join_year',
            field=models.DateField(default=datetime.datetime(2019, 4, 18, 15, 0, 38, 559321, tzinfo=utc), help_text='Select your date of join the college', verbose_name='DOJ'),
        ),
    ]
